package com.streamflix.video.config;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.io.InputStream;
import java.util.List;

/**
 * Loads the video catalog on first boot. Prefers the large cached catalog produced by the OLTP load
 * simulator (classpath:catalog/youtube-catalog-large.json, generated by scripts/youtube-catalog-pull.mjs)
 * and falls back to the curated demo seed (classpath:catalog/youtube-seed.json) when the large file is
 * absent. Videos are metadata only — each row references a real YouTube video by id; the thumbnail is
 * derived from that id. Runs before {@link BehaviorSeeder} (Order 1) so behavior has a catalog to
 * reference. No-ops if the catalog already exists.
 *
 * <p>Rows are inserted in a single JDBC batch so seeding thousands of videos stays fast. The optional
 * {@code description}/{@code releaseYear} fields are present in the large catalog and defaulted for the
 * small demo seed.</p>
 *
 * <p>Optional enrichment: if {@code YOUTUBE_API_KEY} is set, {@link com.streamflix.video.youtube.YoutubeApiCatalogLoader}
 * refreshes titles/durations from the YouTube Data API; otherwise the JSON values are used verbatim.</p>
 */
@Component
@Order(1)
public class CatalogSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(CatalogSeeder.class);
    private static final int BATCH_SIZE = 500;
    private static final String LARGE_CATALOG = "catalog/youtube-catalog-large.json";
    private static final String DEMO_SEED = "catalog/youtube-seed.json";

    /** Superset record: the demo seed omits description/releaseYear, which Jackson leaves null/0. */
    public record SeedVideo(String youtubeId, String title, String genre, String channel,
                            int durationSec, String description, Integer releaseYear) {
    }

    private final JdbcTemplate jdbc;
    private final ObjectMapper mapper;

    public CatalogSeeder(JdbcTemplate jdbc, ObjectMapper mapper) {
        this.jdbc = jdbc;
        this.mapper = mapper;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        Integer count = jdbc.queryForObject("SELECT count(*) FROM videos", Integer.class);
        if (count != null && count > 0) {
            return;
        }
        ClassPathResource large = new ClassPathResource(LARGE_CATALOG);
        String source = large.exists() ? LARGE_CATALOG : DEMO_SEED;
        List<SeedVideo> seed;
        try (InputStream in = new ClassPathResource(source).getInputStream()) {
            seed = List.of(mapper.readValue(in, SeedVideo[].class));
        }
        jdbc.batchUpdate("""
                INSERT INTO videos (youtube_id, title, description, genre, channel, duration_sec, release_year, thumbnail_url)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                seed, BATCH_SIZE,
                (ps, v) -> {
                    String description = v.description() != null ? v.description() : v.channel() + " — " + v.genre();
                    int releaseYear = v.releaseYear() != null && v.releaseYear() > 0 ? v.releaseYear() : 2015;
                    ps.setString(1, v.youtubeId());
                    ps.setString(2, v.title());
                    ps.setString(3, description);
                    ps.setString(4, v.genre());
                    ps.setString(5, v.channel());
                    ps.setInt(6, v.durationSec());
                    ps.setInt(7, releaseYear);
                    ps.setString(8, "https://img.youtube.com/vi/" + v.youtubeId() + "/hqdefault.jpg");
                });
        log.info("CatalogSeeder loaded {} YouTube videos into the catalog (source: {}, batch size {})",
                seed.size(), source, BATCH_SIZE);
    }
}
