#!/usr/bin/env node
// -----------------------------------------------------------------------------
// Turns a k6 run + live Prometheus into a single "how far from Netflix-lite?" report.
//
// Reads loadtest/results/summary.json (written by k6 handleSummary) and loadtest/targets.json,
// optionally queries Prometheus for DB-pool utilization, and emits loadtest/results/gap-report.md:
// a table of  metric | measured | target | pass/fail | % gap  plus a one-line verdict.
//
// Usage:  node scripts/gap-report.mjs [--prom http://localhost:9090]
// -----------------------------------------------------------------------------

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..');
const SUMMARY = resolve(REPO, 'loadtest/results/summary.json');
const TARGETS = resolve(REPO, 'loadtest/targets.json');
const OUT = resolve(REPO, 'loadtest/results/gap-report.md');

const argi = process.argv.indexOf('--prom');
const PROM = argi >= 0 && process.argv[argi + 1] ? process.argv[argi + 1] : 'http://localhost:9090';

if (!existsSync(SUMMARY)) {
  console.error(`ERROR: ${SUMMARY} not found. Run the k6 load test first (docker compose --profile loadtest run --rm k6).`);
  process.exit(1);
}
const summary = JSON.parse(readFileSync(SUMMARY, 'utf8'));
const targets = JSON.parse(readFileSync(TARGETS, 'utf8'));

// metric value helpers (k6 summary schema: metrics[name].values[sub])
const val = (name, sub) => summary.metrics?.[name]?.values?.[sub];

// Prometheus instant query (best-effort; report still works offline).
async function promQuery(q) {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 3000);
    const res = await fetch(`${PROM}/api/v1/query?query=${encodeURIComponent(q)}`, { signal: ctrl.signal });
    clearTimeout(t);
    if (!res.ok) return null;
    const j = await res.json();
    const v = j?.data?.result?.[0]?.value?.[1];
    return v !== undefined ? parseFloat(v) : null;
  } catch {
    return null;
  }
}

// direction: 'lower' = smaller is better (latency/error); 'higher' = larger is better (throughput)
function row(label, measured, target, direction, fmt) {
  if (measured === undefined || measured === null || Number.isNaN(measured)) {
    return { label, measured: 'n/a', target: fmt(target), pass: null, gap: 'n/a' };
  }
  let pass, gapPct;
  if (direction === 'lower') {
    pass = measured <= target;
    gapPct = pass ? 0 : ((measured - target) / target) * 100;
  } else {
    pass = measured >= target * 0.95; // 5% tolerance band on throughput
    gapPct = measured >= target ? 0 : ((target - measured) / target) * 100;
  }
  return {
    label,
    measured: fmt(measured),
    target: fmt(target),
    pass,
    gap: gapPct === 0 ? '0%' : `${gapPct.toFixed(1)}%`,
  };
}

const ms = (v) => `${Number(v).toFixed(1)} ms`;
const pct = (v) => `${(Number(v) * 100).toFixed(2)}%`;
const eps = (v) => `${Number(v).toFixed(1)}/s`;

const poolUtil = await promQuery(
  'max(hikaricp_connections_active{application="video-service"}) / max(hikaricp_connections_max{application="video-service"})',
);

const rows = [
  row('Read p95 latency', val('http_req_duration{group:read}', 'p(95)'), targets.latencyMs.readP95, 'lower', ms),
  row('Write p95 latency', val('http_req_duration{group:write}', 'p(95)'), targets.latencyMs.writeP95, 'lower', ms),
  row('Recommendation p95 latency', val('http_req_duration{group:reco}', 'p(95)'), targets.latencyMs.recommendationP95, 'lower', ms),
  row('Error rate', val('http_req_failed', 'rate'), targets.reliability.errorRateMax, 'lower', pct),
  row('OLTP throughput', val('oltp_events', 'rate'), targets.throughput.targetEventsPerSec, 'higher', eps),
  row('DB pool utilization', poolUtil, targets.reliability.dbPoolUtilizationMax, 'lower', pct),
];

const mark = (p) => (p === null ? '⚠️ n/a' : p ? '✅ pass' : '❌ gap');
const allPass = rows.every((r) => r.pass === true);
const anyFail = rows.some((r) => r.pass === false);

const table = [
  '| Metric | Measured | Target | Status | Gap |',
  '| --- | --- | --- | --- | --- |',
  ...rows.map((r) => `| ${r.label} | ${r.measured} | ${r.target} | ${mark(r.pass)} | ${r.gap} |`),
].join('\n');

const verdict = allPass
  ? '**Verdict: MEETS the lite-Netflix target bar** at this load.'
  : anyFail
    ? '**Verdict: GAP remains** — one or more SLOs are not met at this load (see ❌ rows).'
    : '**Verdict: inconclusive** — some metrics unavailable (⚠️).';

const scaleNote =
  `Target scale: ${targets.scale.catalogVideos} videos, ${targets.scale.users} users, ` +
  `~${targets.throughput.targetEventsPerSec} events/sec.`;

const md = `# StreamFlix — Gap to Lite Netflix-like Platform

_Generated by scripts/gap-report.mjs from the latest k6 run._

${scaleNote}

${table}

${verdict}

> Latency/error/pool are "lower is better"; throughput is "higher is better" (5% tolerance).
> % Gap is how far the measured value is beyond the target (0% = target met).
> DB pool utilization is read live from Prometheus (${PROM}); shows n/a if the monitoring profile is not running.
`;

writeFileSync(OUT, md);
console.log(md);
console.error(`\nWrote ${OUT}`);
